jQuery(function($){$('#theme-selector').on('click',function(event){event.preventDefault()
$('#templates-wrapper').slideToggle(100);$('body').toggleClass('popup-open');$(this).toggleClass('active');});$('.popup-overlay').on('click',function(event){event.preventDefault()
$('#templates-wrapper').slideUp(100);$('body').removeClass('popup-open');$('#theme-selector').removeClass('active');});$('#demoframe').css('height',$(window).height()-73);$('#demoframe').css('width',$(window).width());$(window).on('resize',function(){$('#demoframe').css({'height':$(window).height()-73,'width':$(window).width(),'margin-top':73});$('#demoframe').removeAttr('class');$('#responsive>a').removeClass('active');$('#responsive>#desktop').addClass('active');});var getUrlParameter=function getUrlParameter(sParam){var sPageURL=decodeURIComponent(window.location.search.substring(1)),sURLVariables=sPageURL.split('&'),sParameterName,i;for(i=0;i<sURLVariables.length;i++){sParameterName=sURLVariables[i].split('=');if(sParameterName[0]===sParam){return sParameterName[1]===undefined?true:sParameterName[1];}}};var theme=getUrlParameter('theme');


if ( theme==undefined ){
var ntheme=$('.owl-item:nth-child(2) > [data-slug] > .demo-link');
}
else {
var ntheme=$('[data-slug="'+theme+'"] > .demo-link'); }

  
   

var template_title=ntheme.closest('.template-item').find('.template-title').clone().children().remove().end().text();$('.template-item.active').removeClass('active');ntheme.closest('.template-item').addClass('active');window.history.replaceState("","",'?theme='+ntheme.closest('.template-item').data('slug'));$('.btn-details').attr('href',ntheme.closest('.template-item').data('details'));$('.btn-buy').attr('href',ntheme.closest('.template-item').data('cart'));$('#templates-wrapper').slideUp(100);$('body').removeClass('popup-open');$('#theme-selector').removeClass('active');$('#page-title').text(template_title+' › Live Demo › Paramone');$('.theme-name').text(template_title);$('#demoframe > iframe').removeAttr('src').attr('src',ntheme.attr('href'));$(document.body).addClass('loading');$(document.body).prepend('<div class="preloader"><div></div></div>');$(document).on('click','.demo-link',function(event){event.preventDefault();var template_title=$(this).closest('.template-item').find('.template-title').clone().children().remove().end().text();$('.template-item.active').removeClass('active');$(this).closest('.template-item').addClass('active');window.history.replaceState("","",'?theme='+$(this).closest('.template-item').data('slug'));$('.btn-details').attr('href',$(this).closest('.template-item').data('details'));$('.btn-buy').attr('href',$(this).closest('.template-item').data('cart'));$('#templates-wrapper').slideUp(100);$('body').removeClass('popup-open');$('#theme-selector').removeClass('active');$('#page-title').text(template_title+' › Live Demo › Paramone');$('.theme-name').text(template_title);$('#demoframe > iframe').removeAttr('src').attr('src',$(this).attr('href'));$(document.body).addClass('loading');$(document.body).prepend('<div class="preloader"><div></div></div>');});$('#desktop').on('click',function(event){event.preventDefault()
$('#responsive>a').removeClass('active');$(this).addClass('active');$('#demoframe').removeAttr('class').css({'margin-top':73,'width':$(window).width(),'height':$(window).height()-73});});$('#tablet-landscape').on('click',function(event){event.preventDefault()
$('#responsive>a').removeClass('active');$(this).addClass('active');$('#demoframe').removeAttr('class').addClass('tablet-landscape').css({'margin-top':73,'width':992,'height':$(window).height()-73});});$('#tablet-portrait').on('click',function(event){event.preventDefault()
$('#responsive>a').removeClass('active');$(this).addClass('active');$('#demoframe').removeAttr('class').addClass('tablet-portrait').css({'margin-top':73,'width':768,'height':$(window).height()-73});});$('#phone-landscape').on('click',function(event){event.preventDefault()
$('#responsive>a').removeClass('active');$(this).addClass('active');$('#demoframe').removeAttr('class').addClass('phone-landscape').css({'margin-top':80,'width':768,'height':392});});$('#phone-portrait').on('click',function(event){event.preventDefault()
$('#responsive>a').removeClass('active');$(this).addClass('active');$('#demoframe').removeAttr('class').addClass('phone-portrait').css({'margin-top':80,'width':480,'height':665});});$('#remove-frame').on('click',function(event){event.preventDefault()
var demo=$("#demoframe > iframe").attr('src');window.location=demo;});$('#demoframe > iframe').on('load',function(){$(document.body).removeClass('loading');$(document.body).find('.preloader').remove();});});